# See https://wiki.hyprland.org/Configuring/Binds/

#!
##! Zoom
bind = Shift+Super, mouse_down, exec, hyprctl -q keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '.float * 1.2') # Zoom ↑
bind = Shift+Super, mouse_up, exec, hyprctl -q keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '(.float * 0.5) | if . < 1 then 1 else . end') # Zoom ↓

##! Custom Apps
bind = Super, D, exec, vesktop # Vesktop
bind = SUPER, W, exec, env MOZ_DRM_DEVICE=/dev/dri/renderD128 __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia MOZ_ENABLE_WAYLAND=1 firefox #Firefox
bind = Super, T, exec, env __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia AyuGram #AyuGram
bind = Super, K, exec, keepassxc #KeePassXC
bind = Super, U, exec, kdenlive #Kdenlive
bind = Super, X, exec, spotify #Spotify
